/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var google_cloud_securitycenter_v1_security_marks_pb = require('../../../../google/cloud/securitycenter/v1/security_marks_pb.js');
goog.object.extend(proto, google_cloud_securitycenter_v1_security_marks_pb);
var google_protobuf_struct_pb = require('google-protobuf/google/protobuf/struct_pb.js');
goog.object.extend(proto, google_protobuf_struct_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.google.cloud.securitycenter.v1.Finding', null, global);
goog.exportSymbol('proto.google.cloud.securitycenter.v1.Finding.State', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.securitycenter.v1.Finding = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.securitycenter.v1.Finding, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.securitycenter.v1.Finding.displayName = 'proto.google.cloud.securitycenter.v1.Finding';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.securitycenter.v1.Finding.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.securitycenter.v1.Finding} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.securitycenter.v1.Finding.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    parent: jspb.Message.getFieldWithDefault(msg, 2, ""),
    resourceName: jspb.Message.getFieldWithDefault(msg, 3, ""),
    state: jspb.Message.getFieldWithDefault(msg, 4, 0),
    category: jspb.Message.getFieldWithDefault(msg, 5, ""),
    externalUri: jspb.Message.getFieldWithDefault(msg, 6, ""),
    sourcePropertiesMap: (f = msg.getSourcePropertiesMap()) ? f.toObject(includeInstance, proto.google.protobuf.Value.toObject) : [],
    securityMarks: (f = msg.getSecurityMarks()) && google_cloud_securitycenter_v1_security_marks_pb.SecurityMarks.toObject(includeInstance, f),
    eventTime: (f = msg.getEventTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    createTime: (f = msg.getCreateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.securitycenter.v1.Finding}
 */
proto.google.cloud.securitycenter.v1.Finding.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.securitycenter.v1.Finding;
  return proto.google.cloud.securitycenter.v1.Finding.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.securitycenter.v1.Finding} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.securitycenter.v1.Finding}
 */
proto.google.cloud.securitycenter.v1.Finding.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setParent(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setResourceName(value);
      break;
    case 4:
      var value = /** @type {!proto.google.cloud.securitycenter.v1.Finding.State} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategory(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setExternalUri(value);
      break;
    case 7:
      var value = msg.getSourcePropertiesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.google.protobuf.Value.deserializeBinaryFromReader, "");
         });
      break;
    case 8:
      var value = new google_cloud_securitycenter_v1_security_marks_pb.SecurityMarks;
      reader.readMessage(value,google_cloud_securitycenter_v1_security_marks_pb.SecurityMarks.deserializeBinaryFromReader);
      msg.setSecurityMarks(value);
      break;
    case 9:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setEventTime(value);
      break;
    case 10:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreateTime(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.securitycenter.v1.Finding.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.securitycenter.v1.Finding} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.securitycenter.v1.Finding.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getParent();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getResourceName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getCategory();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getExternalUri();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getSourcePropertiesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(7, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.google.protobuf.Value.serializeBinaryToWriter);
  }
  f = message.getSecurityMarks();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_cloud_securitycenter_v1_security_marks_pb.SecurityMarks.serializeBinaryToWriter
    );
  }
  f = message.getEventTime();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getCreateTime();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.google.cloud.securitycenter.v1.Finding.State = {
  STATE_UNSPECIFIED: 0,
  ACTIVE: 1,
  INACTIVE: 2
};

/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.cloud.securitycenter.v1.Finding.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string parent = 2;
 * @return {string}
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.getParent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.google.cloud.securitycenter.v1.Finding.prototype.setParent = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string resource_name = 3;
 * @return {string}
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.getResourceName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.google.cloud.securitycenter.v1.Finding.prototype.setResourceName = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional State state = 4;
 * @return {!proto.google.cloud.securitycenter.v1.Finding.State}
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.getState = function() {
  return /** @type {!proto.google.cloud.securitycenter.v1.Finding.State} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {!proto.google.cloud.securitycenter.v1.Finding.State} value */
proto.google.cloud.securitycenter.v1.Finding.prototype.setState = function(value) {
  jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional string category = 5;
 * @return {string}
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.getCategory = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.google.cloud.securitycenter.v1.Finding.prototype.setCategory = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string external_uri = 6;
 * @return {string}
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.getExternalUri = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.google.cloud.securitycenter.v1.Finding.prototype.setExternalUri = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * map<string, google.protobuf.Value> source_properties = 7;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.google.protobuf.Value>}
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.getSourcePropertiesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.google.protobuf.Value>} */ (
      jspb.Message.getMapField(this, 7, opt_noLazyCreate,
      proto.google.protobuf.Value));
};


/**
 * Clears values from the map. The map will be non-null.
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.clearSourcePropertiesMap = function() {
  this.getSourcePropertiesMap().clear();
};


/**
 * optional SecurityMarks security_marks = 8;
 * @return {?proto.google.cloud.securitycenter.v1.SecurityMarks}
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.getSecurityMarks = function() {
  return /** @type{?proto.google.cloud.securitycenter.v1.SecurityMarks} */ (
    jspb.Message.getWrapperField(this, google_cloud_securitycenter_v1_security_marks_pb.SecurityMarks, 8));
};


/** @param {?proto.google.cloud.securitycenter.v1.SecurityMarks|undefined} value */
proto.google.cloud.securitycenter.v1.Finding.prototype.setSecurityMarks = function(value) {
  jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.clearSecurityMarks = function() {
  this.setSecurityMarks(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.hasSecurityMarks = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * optional google.protobuf.Timestamp event_time = 9;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.getEventTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 9));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.google.cloud.securitycenter.v1.Finding.prototype.setEventTime = function(value) {
  jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.clearEventTime = function() {
  this.setEventTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.hasEventTime = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional google.protobuf.Timestamp create_time = 10;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.getCreateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 10));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.google.cloud.securitycenter.v1.Finding.prototype.setCreateTime = function(value) {
  jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.clearCreateTime = function() {
  this.setCreateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.securitycenter.v1.Finding.prototype.hasCreateTime = function() {
  return jspb.Message.getField(this, 10) != null;
};


goog.object.extend(exports, proto.google.cloud.securitycenter.v1);
