/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var google_protobuf_duration_pb = require('google-protobuf/google/protobuf/duration_pb.js');
goog.object.extend(proto, google_protobuf_duration_pb);
goog.exportSymbol('proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig', null, global);
goog.exportSymbol('proto.google.cloud.datalabeling.v1beta1.EventConfig', null, global);
goog.exportSymbol('proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig', null, global);
goog.exportSymbol('proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig', null, global);
goog.exportSymbol('proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig', null, global);
goog.exportSymbol('proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig', null, global);
goog.exportSymbol('proto.google.cloud.datalabeling.v1beta1.PolylineConfig', null, global);
goog.exportSymbol('proto.google.cloud.datalabeling.v1beta1.SegmentationConfig', null, global);
goog.exportSymbol('proto.google.cloud.datalabeling.v1beta1.SentimentConfig', null, global);
goog.exportSymbol('proto.google.cloud.datalabeling.v1beta1.StringAggregationType', null, global);
goog.exportSymbol('proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig', null, global);
goog.exportSymbol('proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig', null, global);
goog.exportSymbol('proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig', null, global);
goog.exportSymbol('proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.displayName = 'proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig.displayName = 'proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig.displayName = 'proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.datalabeling.v1beta1.PolylineConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.datalabeling.v1beta1.PolylineConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.datalabeling.v1beta1.PolylineConfig.displayName = 'proto.google.cloud.datalabeling.v1beta1.PolylineConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.datalabeling.v1beta1.SegmentationConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.datalabeling.v1beta1.SegmentationConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.datalabeling.v1beta1.SegmentationConfig.displayName = 'proto.google.cloud.datalabeling.v1beta1.SegmentationConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.displayName = 'proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.displayName = 'proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig.displayName = 'proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig.displayName = 'proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.datalabeling.v1beta1.EventConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.datalabeling.v1beta1.EventConfig.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.datalabeling.v1beta1.EventConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.datalabeling.v1beta1.EventConfig.displayName = 'proto.google.cloud.datalabeling.v1beta1.EventConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.displayName = 'proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.datalabeling.v1beta1.SentimentConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.datalabeling.v1beta1.SentimentConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.datalabeling.v1beta1.SentimentConfig.displayName = 'proto.google.cloud.datalabeling.v1beta1.SentimentConfig';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig.displayName = 'proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.repeatedFields_ = [9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    instruction: jspb.Message.getFieldWithDefault(msg, 1, ""),
    annotatedDatasetDisplayName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    annotatedDatasetDescription: jspb.Message.getFieldWithDefault(msg, 3, ""),
    labelGroup: jspb.Message.getFieldWithDefault(msg, 4, ""),
    languageCode: jspb.Message.getFieldWithDefault(msg, 5, ""),
    replicaCount: jspb.Message.getFieldWithDefault(msg, 6, 0),
    questionDuration: (f = msg.getQuestionDuration()) && google_protobuf_duration_pb.Duration.toObject(includeInstance, f),
    contributorEmailsList: (f = jspb.Message.getRepeatedField(msg, 9)) == null ? undefined : f,
    userEmailAddress: jspb.Message.getFieldWithDefault(msg, 10, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig}
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig;
  return proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig}
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setInstruction(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnnotatedDatasetDisplayName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnnotatedDatasetDescription(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setLabelGroup(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguageCode(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setReplicaCount(value);
      break;
    case 7:
      var value = new google_protobuf_duration_pb.Duration;
      reader.readMessage(value,google_protobuf_duration_pb.Duration.deserializeBinaryFromReader);
      msg.setQuestionDuration(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.addContributorEmails(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setUserEmailAddress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInstruction();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAnnotatedDatasetDisplayName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getAnnotatedDatasetDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLabelGroup();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getLanguageCode();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getReplicaCount();
  if (f !== 0) {
    writer.writeInt32(
      6,
      f
    );
  }
  f = message.getQuestionDuration();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_protobuf_duration_pb.Duration.serializeBinaryToWriter
    );
  }
  f = message.getContributorEmailsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      9,
      f
    );
  }
  f = message.getUserEmailAddress();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
};


/**
 * optional string instruction = 1;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.getInstruction = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.setInstruction = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string annotated_dataset_display_name = 2;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.getAnnotatedDatasetDisplayName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.setAnnotatedDatasetDisplayName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string annotated_dataset_description = 3;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.getAnnotatedDatasetDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.setAnnotatedDatasetDescription = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string label_group = 4;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.getLabelGroup = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.setLabelGroup = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string language_code = 5;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.getLanguageCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.setLanguageCode = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional int32 replica_count = 6;
 * @return {number}
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.getReplicaCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.setReplicaCount = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional google.protobuf.Duration question_duration = 7;
 * @return {?proto.google.protobuf.Duration}
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.getQuestionDuration = function() {
  return /** @type{?proto.google.protobuf.Duration} */ (
    jspb.Message.getWrapperField(this, google_protobuf_duration_pb.Duration, 7));
};


/** @param {?proto.google.protobuf.Duration|undefined} value */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.setQuestionDuration = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.clearQuestionDuration = function() {
  this.setQuestionDuration(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.hasQuestionDuration = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * repeated string contributor_emails = 9;
 * @return {!Array<string>}
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.getContributorEmailsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 9));
};


/** @param {!Array<string>} value */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.setContributorEmailsList = function(value) {
  jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.addContributorEmails = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.clearContributorEmailsList = function() {
  this.setContributorEmailsList([]);
};


/**
 * optional string user_email_address = 10;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.getUserEmailAddress = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.HumanAnnotationConfig.prototype.setUserEmailAddress = function(value) {
  jspb.Message.setProto3StringField(this, 10, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    annotationSpecSet: jspb.Message.getFieldWithDefault(msg, 1, ""),
    allowMultiLabel: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    answerAggregationType: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig}
 */
proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig;
  return proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig}
 */
proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnnotationSpecSet(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAllowMultiLabel(value);
      break;
    case 3:
      var value = /** @type {!proto.google.cloud.datalabeling.v1beta1.StringAggregationType} */ (reader.readEnum());
      msg.setAnswerAggregationType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnnotationSpecSet();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAllowMultiLabel();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
  f = message.getAnswerAggregationType();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
};


/**
 * optional string annotation_spec_set = 1;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig.prototype.getAnnotationSpecSet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig.prototype.setAnnotationSpecSet = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool allow_multi_label = 2;
 * @return {boolean}
 */
proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig.prototype.getAllowMultiLabel = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig.prototype.setAllowMultiLabel = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * optional StringAggregationType answer_aggregation_type = 3;
 * @return {!proto.google.cloud.datalabeling.v1beta1.StringAggregationType}
 */
proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig.prototype.getAnswerAggregationType = function() {
  return /** @type {!proto.google.cloud.datalabeling.v1beta1.StringAggregationType} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {!proto.google.cloud.datalabeling.v1beta1.StringAggregationType} value */
proto.google.cloud.datalabeling.v1beta1.ImageClassificationConfig.prototype.setAnswerAggregationType = function(value) {
  jspb.Message.setProto3EnumField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    annotationSpecSet: jspb.Message.getFieldWithDefault(msg, 1, ""),
    instructionMessage: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig}
 */
proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig;
  return proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig}
 */
proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnnotationSpecSet(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setInstructionMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnnotationSpecSet();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInstructionMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string annotation_spec_set = 1;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig.prototype.getAnnotationSpecSet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig.prototype.setAnnotationSpecSet = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string instruction_message = 2;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig.prototype.getInstructionMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.BoundingPolyConfig.prototype.setInstructionMessage = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.datalabeling.v1beta1.PolylineConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.datalabeling.v1beta1.PolylineConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.datalabeling.v1beta1.PolylineConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.PolylineConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    annotationSpecSet: jspb.Message.getFieldWithDefault(msg, 1, ""),
    instructionMessage: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.datalabeling.v1beta1.PolylineConfig}
 */
proto.google.cloud.datalabeling.v1beta1.PolylineConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.datalabeling.v1beta1.PolylineConfig;
  return proto.google.cloud.datalabeling.v1beta1.PolylineConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.datalabeling.v1beta1.PolylineConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.datalabeling.v1beta1.PolylineConfig}
 */
proto.google.cloud.datalabeling.v1beta1.PolylineConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnnotationSpecSet(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setInstructionMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.datalabeling.v1beta1.PolylineConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.datalabeling.v1beta1.PolylineConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.datalabeling.v1beta1.PolylineConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.PolylineConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnnotationSpecSet();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInstructionMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string annotation_spec_set = 1;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.PolylineConfig.prototype.getAnnotationSpecSet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.PolylineConfig.prototype.setAnnotationSpecSet = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string instruction_message = 2;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.PolylineConfig.prototype.getInstructionMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.PolylineConfig.prototype.setInstructionMessage = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.datalabeling.v1beta1.SegmentationConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.datalabeling.v1beta1.SegmentationConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.datalabeling.v1beta1.SegmentationConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.SegmentationConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    annotationSpecSet: jspb.Message.getFieldWithDefault(msg, 1, ""),
    instructionMessage: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.datalabeling.v1beta1.SegmentationConfig}
 */
proto.google.cloud.datalabeling.v1beta1.SegmentationConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.datalabeling.v1beta1.SegmentationConfig;
  return proto.google.cloud.datalabeling.v1beta1.SegmentationConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.datalabeling.v1beta1.SegmentationConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.datalabeling.v1beta1.SegmentationConfig}
 */
proto.google.cloud.datalabeling.v1beta1.SegmentationConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnnotationSpecSet(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setInstructionMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.datalabeling.v1beta1.SegmentationConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.datalabeling.v1beta1.SegmentationConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.datalabeling.v1beta1.SegmentationConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.SegmentationConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnnotationSpecSet();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInstructionMessage();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string annotation_spec_set = 1;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.SegmentationConfig.prototype.getAnnotationSpecSet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.SegmentationConfig.prototype.setAnnotationSpecSet = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string instruction_message = 2;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.SegmentationConfig.prototype.getInstructionMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.SegmentationConfig.prototype.setInstructionMessage = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    annotationSpecSetConfigsList: jspb.Message.toObjectList(msg.getAnnotationSpecSetConfigsList(),
    proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.toObject, includeInstance),
    applyShotDetection: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig}
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig;
  return proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig}
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig;
      reader.readMessage(value,proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.deserializeBinaryFromReader);
      msg.addAnnotationSpecSetConfigs(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setApplyShotDetection(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnnotationSpecSetConfigsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.serializeBinaryToWriter
    );
  }
  f = message.getApplyShotDetection();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    annotationSpecSet: jspb.Message.getFieldWithDefault(msg, 1, ""),
    allowMultiLabel: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig}
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig;
  return proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig}
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnnotationSpecSet(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAllowMultiLabel(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnnotationSpecSet();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAllowMultiLabel();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * optional string annotation_spec_set = 1;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.prototype.getAnnotationSpecSet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.prototype.setAnnotationSpecSet = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bool allow_multi_label = 2;
 * @return {boolean}
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.prototype.getAllowMultiLabel = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig.prototype.setAllowMultiLabel = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};


/**
 * repeated AnnotationSpecSetConfig annotation_spec_set_configs = 1;
 * @return {!Array<!proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig>}
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.prototype.getAnnotationSpecSetConfigsList = function() {
  return /** @type{!Array<!proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig, 1));
};


/** @param {!Array<!proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig>} value */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.prototype.setAnnotationSpecSetConfigsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig}
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.prototype.addAnnotationSpecSetConfigs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.AnnotationSpecSetConfig, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.prototype.clearAnnotationSpecSetConfigsList = function() {
  this.setAnnotationSpecSetConfigsList([]);
};


/**
 * optional bool apply_shot_detection = 2;
 * @return {boolean}
 */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.prototype.getApplyShotDetection = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/** @param {boolean} value */
proto.google.cloud.datalabeling.v1beta1.VideoClassificationConfig.prototype.setApplyShotDetection = function(value) {
  jspb.Message.setProto3BooleanField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    annotationSpecSet: jspb.Message.getFieldWithDefault(msg, 1, ""),
    extractionFrameRate: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig}
 */
proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig;
  return proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig}
 */
proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnnotationSpecSet(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setExtractionFrameRate(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnnotationSpecSet();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getExtractionFrameRate();
  if (f !== 0.0) {
    writer.writeDouble(
      3,
      f
    );
  }
};


/**
 * optional string annotation_spec_set = 1;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig.prototype.getAnnotationSpecSet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig.prototype.setAnnotationSpecSet = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional double extraction_frame_rate = 3;
 * @return {number}
 */
proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig.prototype.getExtractionFrameRate = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/** @param {number} value */
proto.google.cloud.datalabeling.v1beta1.ObjectDetectionConfig.prototype.setExtractionFrameRate = function(value) {
  jspb.Message.setProto3FloatField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    annotationSpecSet: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig}
 */
proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig;
  return proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig}
 */
proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnnotationSpecSet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnnotationSpecSet();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string annotation_spec_set = 1;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig.prototype.getAnnotationSpecSet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.ObjectTrackingConfig.prototype.setAnnotationSpecSet = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.datalabeling.v1beta1.EventConfig.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.datalabeling.v1beta1.EventConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.datalabeling.v1beta1.EventConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.datalabeling.v1beta1.EventConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.EventConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    annotationSpecSetsList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.datalabeling.v1beta1.EventConfig}
 */
proto.google.cloud.datalabeling.v1beta1.EventConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.datalabeling.v1beta1.EventConfig;
  return proto.google.cloud.datalabeling.v1beta1.EventConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.datalabeling.v1beta1.EventConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.datalabeling.v1beta1.EventConfig}
 */
proto.google.cloud.datalabeling.v1beta1.EventConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addAnnotationSpecSets(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.datalabeling.v1beta1.EventConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.datalabeling.v1beta1.EventConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.datalabeling.v1beta1.EventConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.EventConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnnotationSpecSetsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
};


/**
 * repeated string annotation_spec_sets = 1;
 * @return {!Array<string>}
 */
proto.google.cloud.datalabeling.v1beta1.EventConfig.prototype.getAnnotationSpecSetsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array<string>} value */
proto.google.cloud.datalabeling.v1beta1.EventConfig.prototype.setAnnotationSpecSetsList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 */
proto.google.cloud.datalabeling.v1beta1.EventConfig.prototype.addAnnotationSpecSets = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.google.cloud.datalabeling.v1beta1.EventConfig.prototype.clearAnnotationSpecSetsList = function() {
  this.setAnnotationSpecSetsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    allowMultiLabel: jspb.Message.getBooleanFieldWithDefault(msg, 1, false),
    annotationSpecSet: jspb.Message.getFieldWithDefault(msg, 2, ""),
    sentimentConfig: (f = msg.getSentimentConfig()) && proto.google.cloud.datalabeling.v1beta1.SentimentConfig.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig}
 */
proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig;
  return proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig}
 */
proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setAllowMultiLabel(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnnotationSpecSet(value);
      break;
    case 3:
      var value = new proto.google.cloud.datalabeling.v1beta1.SentimentConfig;
      reader.readMessage(value,proto.google.cloud.datalabeling.v1beta1.SentimentConfig.deserializeBinaryFromReader);
      msg.setSentimentConfig(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAllowMultiLabel();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
  f = message.getAnnotationSpecSet();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSentimentConfig();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.google.cloud.datalabeling.v1beta1.SentimentConfig.serializeBinaryToWriter
    );
  }
};


/**
 * optional bool allow_multi_label = 1;
 * @return {boolean}
 */
proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.prototype.getAllowMultiLabel = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.prototype.setAllowMultiLabel = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};


/**
 * optional string annotation_spec_set = 2;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.prototype.getAnnotationSpecSet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.prototype.setAnnotationSpecSet = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional SentimentConfig sentiment_config = 3;
 * @return {?proto.google.cloud.datalabeling.v1beta1.SentimentConfig}
 */
proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.prototype.getSentimentConfig = function() {
  return /** @type{?proto.google.cloud.datalabeling.v1beta1.SentimentConfig} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.datalabeling.v1beta1.SentimentConfig, 3));
};


/** @param {?proto.google.cloud.datalabeling.v1beta1.SentimentConfig|undefined} value */
proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.prototype.setSentimentConfig = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.prototype.clearSentimentConfig = function() {
  this.setSentimentConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.datalabeling.v1beta1.TextClassificationConfig.prototype.hasSentimentConfig = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.datalabeling.v1beta1.SentimentConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.datalabeling.v1beta1.SentimentConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.datalabeling.v1beta1.SentimentConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.SentimentConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    enableLabelSentimentSelection: jspb.Message.getBooleanFieldWithDefault(msg, 1, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.datalabeling.v1beta1.SentimentConfig}
 */
proto.google.cloud.datalabeling.v1beta1.SentimentConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.datalabeling.v1beta1.SentimentConfig;
  return proto.google.cloud.datalabeling.v1beta1.SentimentConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.datalabeling.v1beta1.SentimentConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.datalabeling.v1beta1.SentimentConfig}
 */
proto.google.cloud.datalabeling.v1beta1.SentimentConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setEnableLabelSentimentSelection(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.datalabeling.v1beta1.SentimentConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.datalabeling.v1beta1.SentimentConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.datalabeling.v1beta1.SentimentConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.SentimentConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnableLabelSentimentSelection();
  if (f) {
    writer.writeBool(
      1,
      f
    );
  }
};


/**
 * optional bool enable_label_sentiment_selection = 1;
 * @return {boolean}
 */
proto.google.cloud.datalabeling.v1beta1.SentimentConfig.prototype.getEnableLabelSentimentSelection = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 1, false));
};


/** @param {boolean} value */
proto.google.cloud.datalabeling.v1beta1.SentimentConfig.prototype.setEnableLabelSentimentSelection = function(value) {
  jspb.Message.setProto3BooleanField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig.toObject = function(includeInstance, msg) {
  var f, obj = {
    annotationSpecSet: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig}
 */
proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig;
  return proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig}
 */
proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAnnotationSpecSet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAnnotationSpecSet();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string annotation_spec_set = 1;
 * @return {string}
 */
proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig.prototype.getAnnotationSpecSet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.cloud.datalabeling.v1beta1.TextEntityExtractionConfig.prototype.setAnnotationSpecSet = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * @enum {number}
 */
proto.google.cloud.datalabeling.v1beta1.StringAggregationType = {
  STRING_AGGREGATION_TYPE_UNSPECIFIED: 0,
  MAJORITY_VOTE: 1,
  UNANIMOUS_VOTE: 2,
  NO_AGGREGATION: 3
};

goog.object.extend(exports, proto.google.cloud.datalabeling.v1beta1);
