/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_api_annotations_pb = require('../../../../google/api/annotations_pb.js');
goog.object.extend(proto, google_api_annotations_pb);
var google_api_field_behavior_pb = require('../../../../google/api/field_behavior_pb.js');
goog.object.extend(proto, google_api_field_behavior_pb);
var google_cloud_talent_v4beta1_common_pb = require('../../../../google/cloud/talent/v4beta1/common_pb.js');
goog.object.extend(proto, google_cloud_talent_v4beta1_common_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
var google_protobuf_wrappers_pb = require('google-protobuf/google/protobuf/wrappers_pb.js');
goog.object.extend(proto, google_protobuf_wrappers_pb);
var google_type_date_pb = require('../../../../google/type/date_pb.js');
goog.object.extend(proto, google_type_date_pb);
goog.exportSymbol('proto.google.cloud.talent.v4beta1.Application', null, global);
goog.exportSymbol('proto.google.cloud.talent.v4beta1.Application.ApplicationStage', null, global);
goog.exportSymbol('proto.google.cloud.talent.v4beta1.Application.ApplicationState', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.talent.v4beta1.Application = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.talent.v4beta1.Application.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.talent.v4beta1.Application, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.talent.v4beta1.Application.displayName = 'proto.google.cloud.talent.v4beta1.Application';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.talent.v4beta1.Application.repeatedFields_ = [16];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.talent.v4beta1.Application.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.talent.v4beta1.Application} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.talent.v4beta1.Application.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    externalId: jspb.Message.getFieldWithDefault(msg, 31, ""),
    profile: jspb.Message.getFieldWithDefault(msg, 2, ""),
    job: jspb.Message.getFieldWithDefault(msg, 4, ""),
    company: jspb.Message.getFieldWithDefault(msg, 5, ""),
    applicationDate: (f = msg.getApplicationDate()) && google_type_date_pb.Date.toObject(includeInstance, f),
    stage: jspb.Message.getFieldWithDefault(msg, 11, 0),
    state: jspb.Message.getFieldWithDefault(msg, 13, 0),
    interviewsList: jspb.Message.toObjectList(msg.getInterviewsList(),
    google_cloud_talent_v4beta1_common_pb.Interview.toObject, includeInstance),
    referral: (f = msg.getReferral()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    createTime: (f = msg.getCreateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    updateTime: (f = msg.getUpdateTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    outcomeNotes: jspb.Message.getFieldWithDefault(msg, 21, ""),
    outcome: jspb.Message.getFieldWithDefault(msg, 22, 0),
    isMatch: (f = msg.getIsMatch()) && google_protobuf_wrappers_pb.BoolValue.toObject(includeInstance, f),
    jobTitleSnippet: jspb.Message.getFieldWithDefault(msg, 29, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.talent.v4beta1.Application}
 */
proto.google.cloud.talent.v4beta1.Application.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.talent.v4beta1.Application;
  return proto.google.cloud.talent.v4beta1.Application.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.talent.v4beta1.Application} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.talent.v4beta1.Application}
 */
proto.google.cloud.talent.v4beta1.Application.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 31:
      var value = /** @type {string} */ (reader.readString());
      msg.setExternalId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setProfile(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setJob(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCompany(value);
      break;
    case 7:
      var value = new google_type_date_pb.Date;
      reader.readMessage(value,google_type_date_pb.Date.deserializeBinaryFromReader);
      msg.setApplicationDate(value);
      break;
    case 11:
      var value = /** @type {!proto.google.cloud.talent.v4beta1.Application.ApplicationStage} */ (reader.readEnum());
      msg.setStage(value);
      break;
    case 13:
      var value = /** @type {!proto.google.cloud.talent.v4beta1.Application.ApplicationState} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 16:
      var value = new google_cloud_talent_v4beta1_common_pb.Interview;
      reader.readMessage(value,google_cloud_talent_v4beta1_common_pb.Interview.deserializeBinaryFromReader);
      msg.addInterviews(value);
      break;
    case 18:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setReferral(value);
      break;
    case 19:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setCreateTime(value);
      break;
    case 20:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setUpdateTime(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setOutcomeNotes(value);
      break;
    case 22:
      var value = /** @type {!proto.google.cloud.talent.v4beta1.Outcome} */ (reader.readEnum());
      msg.setOutcome(value);
      break;
    case 28:
      var value = new google_protobuf_wrappers_pb.BoolValue;
      reader.readMessage(value,google_protobuf_wrappers_pb.BoolValue.deserializeBinaryFromReader);
      msg.setIsMatch(value);
      break;
    case 29:
      var value = /** @type {string} */ (reader.readString());
      msg.setJobTitleSnippet(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.talent.v4beta1.Application.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.talent.v4beta1.Application} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.talent.v4beta1.Application.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getExternalId();
  if (f.length > 0) {
    writer.writeString(
      31,
      f
    );
  }
  f = message.getProfile();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getJob();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getCompany();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getApplicationDate();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      google_type_date_pb.Date.serializeBinaryToWriter
    );
  }
  f = message.getStage();
  if (f !== 0.0) {
    writer.writeEnum(
      11,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      13,
      f
    );
  }
  f = message.getInterviewsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      16,
      f,
      google_cloud_talent_v4beta1_common_pb.Interview.serializeBinaryToWriter
    );
  }
  f = message.getReferral();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getCreateTime();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getUpdateTime();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getOutcomeNotes();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getOutcome();
  if (f !== 0.0) {
    writer.writeEnum(
      22,
      f
    );
  }
  f = message.getIsMatch();
  if (f != null) {
    writer.writeMessage(
      28,
      f,
      google_protobuf_wrappers_pb.BoolValue.serializeBinaryToWriter
    );
  }
  f = message.getJobTitleSnippet();
  if (f.length > 0) {
    writer.writeString(
      29,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.google.cloud.talent.v4beta1.Application.ApplicationState = {
  APPLICATION_STATE_UNSPECIFIED: 0,
  IN_PROGRESS: 1,
  CANDIDATE_WITHDREW: 2,
  EMPLOYER_WITHDREW: 3,
  COMPLETED: 4,
  CLOSED: 5
};

/**
 * @enum {number}
 */
proto.google.cloud.talent.v4beta1.Application.ApplicationStage = {
  APPLICATION_STAGE_UNSPECIFIED: 0,
  NEW: 1,
  SCREEN: 2,
  HIRING_MANAGER_REVIEW: 3,
  INTERVIEW: 4,
  OFFER_EXTENDED: 5,
  OFFER_ACCEPTED: 6,
  STARTED: 7
};

/**
 * optional string name = 1;
 * @return {string}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.google.cloud.talent.v4beta1.Application.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string external_id = 31;
 * @return {string}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.getExternalId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 31, ""));
};


/** @param {string} value */
proto.google.cloud.talent.v4beta1.Application.prototype.setExternalId = function(value) {
  jspb.Message.setProto3StringField(this, 31, value);
};


/**
 * optional string profile = 2;
 * @return {string}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.getProfile = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.google.cloud.talent.v4beta1.Application.prototype.setProfile = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string job = 4;
 * @return {string}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.getJob = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.google.cloud.talent.v4beta1.Application.prototype.setJob = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string company = 5;
 * @return {string}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.getCompany = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.google.cloud.talent.v4beta1.Application.prototype.setCompany = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional google.type.Date application_date = 7;
 * @return {?proto.google.type.Date}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.getApplicationDate = function() {
  return /** @type{?proto.google.type.Date} */ (
    jspb.Message.getWrapperField(this, google_type_date_pb.Date, 7));
};


/** @param {?proto.google.type.Date|undefined} value */
proto.google.cloud.talent.v4beta1.Application.prototype.setApplicationDate = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.google.cloud.talent.v4beta1.Application.prototype.clearApplicationDate = function() {
  this.setApplicationDate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.hasApplicationDate = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional ApplicationStage stage = 11;
 * @return {!proto.google.cloud.talent.v4beta1.Application.ApplicationStage}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.getStage = function() {
  return /** @type {!proto.google.cloud.talent.v4beta1.Application.ApplicationStage} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {!proto.google.cloud.talent.v4beta1.Application.ApplicationStage} value */
proto.google.cloud.talent.v4beta1.Application.prototype.setStage = function(value) {
  jspb.Message.setProto3EnumField(this, 11, value);
};


/**
 * optional ApplicationState state = 13;
 * @return {!proto.google.cloud.talent.v4beta1.Application.ApplicationState}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.getState = function() {
  return /** @type {!proto.google.cloud.talent.v4beta1.Application.ApplicationState} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/** @param {!proto.google.cloud.talent.v4beta1.Application.ApplicationState} value */
proto.google.cloud.talent.v4beta1.Application.prototype.setState = function(value) {
  jspb.Message.setProto3EnumField(this, 13, value);
};


/**
 * repeated Interview interviews = 16;
 * @return {!Array<!proto.google.cloud.talent.v4beta1.Interview>}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.getInterviewsList = function() {
  return /** @type{!Array<!proto.google.cloud.talent.v4beta1.Interview>} */ (
    jspb.Message.getRepeatedWrapperField(this, google_cloud_talent_v4beta1_common_pb.Interview, 16));
};


/** @param {!Array<!proto.google.cloud.talent.v4beta1.Interview>} value */
proto.google.cloud.talent.v4beta1.Application.prototype.setInterviewsList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 16, value);
};


/**
 * @param {!proto.google.cloud.talent.v4beta1.Interview=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.talent.v4beta1.Interview}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.addInterviews = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 16, opt_value, proto.google.cloud.talent.v4beta1.Interview, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 */
proto.google.cloud.talent.v4beta1.Application.prototype.clearInterviewsList = function() {
  this.setInterviewsList([]);
};


/**
 * optional google.protobuf.BoolValue referral = 18;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.getReferral = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 18));
};


/** @param {?proto.google.protobuf.BoolValue|undefined} value */
proto.google.cloud.talent.v4beta1.Application.prototype.setReferral = function(value) {
  jspb.Message.setWrapperField(this, 18, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.google.cloud.talent.v4beta1.Application.prototype.clearReferral = function() {
  this.setReferral(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.hasReferral = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional google.protobuf.Timestamp create_time = 19;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.getCreateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 19));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.google.cloud.talent.v4beta1.Application.prototype.setCreateTime = function(value) {
  jspb.Message.setWrapperField(this, 19, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.google.cloud.talent.v4beta1.Application.prototype.clearCreateTime = function() {
  this.setCreateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.hasCreateTime = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional google.protobuf.Timestamp update_time = 20;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.getUpdateTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 20));
};


/** @param {?proto.google.protobuf.Timestamp|undefined} value */
proto.google.cloud.talent.v4beta1.Application.prototype.setUpdateTime = function(value) {
  jspb.Message.setWrapperField(this, 20, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.google.cloud.talent.v4beta1.Application.prototype.clearUpdateTime = function() {
  this.setUpdateTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.hasUpdateTime = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional string outcome_notes = 21;
 * @return {string}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.getOutcomeNotes = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/** @param {string} value */
proto.google.cloud.talent.v4beta1.Application.prototype.setOutcomeNotes = function(value) {
  jspb.Message.setProto3StringField(this, 21, value);
};


/**
 * optional Outcome outcome = 22;
 * @return {!proto.google.cloud.talent.v4beta1.Outcome}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.getOutcome = function() {
  return /** @type {!proto.google.cloud.talent.v4beta1.Outcome} */ (jspb.Message.getFieldWithDefault(this, 22, 0));
};


/** @param {!proto.google.cloud.talent.v4beta1.Outcome} value */
proto.google.cloud.talent.v4beta1.Application.prototype.setOutcome = function(value) {
  jspb.Message.setProto3EnumField(this, 22, value);
};


/**
 * optional google.protobuf.BoolValue is_match = 28;
 * @return {?proto.google.protobuf.BoolValue}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.getIsMatch = function() {
  return /** @type{?proto.google.protobuf.BoolValue} */ (
    jspb.Message.getWrapperField(this, google_protobuf_wrappers_pb.BoolValue, 28));
};


/** @param {?proto.google.protobuf.BoolValue|undefined} value */
proto.google.cloud.talent.v4beta1.Application.prototype.setIsMatch = function(value) {
  jspb.Message.setWrapperField(this, 28, value);
};


/**
 * Clears the message field making it undefined.
 */
proto.google.cloud.talent.v4beta1.Application.prototype.clearIsMatch = function() {
  this.setIsMatch(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.hasIsMatch = function() {
  return jspb.Message.getField(this, 28) != null;
};


/**
 * optional string job_title_snippet = 29;
 * @return {string}
 */
proto.google.cloud.talent.v4beta1.Application.prototype.getJobTitleSnippet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 29, ""));
};


/** @param {string} value */
proto.google.cloud.talent.v4beta1.Application.prototype.setJobTitleSnippet = function(value) {
  jspb.Message.setProto3StringField(this, 29, value);
};


goog.object.extend(exports, proto.google.cloud.talent.v4beta1);
